on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksworkshopwelyacr.azurecr.io
        username: ${{ secrets.acr_aksworkshopwelyacr_username }}
        password: ${{ secrets.acr_aksworkshopwelyacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AcrHelloworld" -f  "AcrHelloworld/Dockerfile" -t aksworkshopwelyacr.azurecr.io/welyaks2:${{ github.sha }}
        docker push aksworkshopwelyacr.azurecr.io/welyaks2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_welyaks2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep helloworldns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace helloworldns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: helloworldns
        container-registry-url: aksworkshopwelyacr.azurecr.io
        container-registry-username: ${{ secrets.acr_aksworkshopwelyacr_username }}
        container-registry-password: ${{ secrets.acr_aksworkshopwelyacr_password }}
        secret-name: welyaks2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: helloworldns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksworkshopwelyacr.azurecr.io/welyaks2:${{ github.sha }}
        imagepullsecrets: |
          welyaks2dockerauth